### ISSUE TITLE
Does it supports Visual studio using NDK ?

### ISSUE THREAD

**Issue by graysuit** [overlisted/rdui#1]
Respected developer @overlisted, 

**Visual studio** do supports **android ndk** (native development kit) and builds 100% **native** apks.
**Rawdrawandroid** is also pure **native**. I am sure it uses ndk.
Does **rdui** supports ndk ? 
If yes, then how ?

Regards

**Comment by overlisted** [comment]
I haven't tried to use the project on Android, but you can fork it and try to make it use rawdrawandroid.

**Comment by graysuit** [comment]
> 
> 
> I haven't tried to use this project on Android, but you can fork it and try to make it use rawdrawandroid.

Yeah sure, C is portable.
Is this project is for windows ?

**Comment by overlisted** [comment]
> Is this project is for windows ?

I test every commit on Wine, so it should be somewhat compatible with Windows.

**Comment by graysuit** [comment]
> 
> 
> > Is this project is for windows ?
> 
> I test every commit on Wine, so it should be somewhat compatible with Windows.

I am sure if it works in sandbox like wine, then I hope it would work well on windows as well.
I tried sample, and was working fine.
